#125 hack aubg animation
AUBGTheHUB/spa-website-2022 pull request #202
Opened 2023-02-04 19:18 UTC by SuelaCark

Added initial structure, gif background image and fixed responsiveness

2023-02-04 23:46 UTC, asynchroza requested changes

2023-02-04 23:46 UTC, asynchroza commented on packages/web/src/components/spa/HackAUBG/LandingAnimation/InvokeAnimation.jsx
> +import { AnimateMatrix } from './landing_animate';
This file should be removed

2023-02-04 23:46 UTC, asynchroza commented on packages/web/src/components/spa/HackAUBG/LandingAnimation/LandingAnimation.jsx
> +// import { InvokeAnimation } from './InvokeAnimation';
Please remove comments which are not describing any specific behaviour

2023-02-04 23:46 UTC, asynchroza commented on packages/web/src/components/spa/HackAUBG/LandingAnimation/landing_animate.js
> +export const AnimateMatrix = () => {
This file should be removed as well.

2023-02-04 23:46 UTC, asynchroza commented on packages/web/src/components/spa/HackAUBG/LandingAnimation/landing_animation.css
> +    display: flex;
Remove leftover css for the js animation if any.

2023-02-05 00:03 UTC, asynchroza commented
Delete redundant gif file as well.

2023-02-06 13:11 UTC, SuelaCark commented
Please dont merge this PR yet, there are some responsiveness issues that I have to resolve first.

2023-02-06 17:51 UTC, asynchroza commented
Remove old animation files

2023-02-07 23:33 UTC, asynchroza commented
@SuelaCark click on resolve whenever you're done applying the specific changes. Most are resolved now but there is still a leftover file which shouldn't be there.

Remove it and ping somebody on @AUBGTheHUB/nosyncdev to approve it tomorrow.

2023-02-08 11:58 UTC, SuelaCark commented
@AUBGTheHUB/nosyncdev Please review this PR. (@r-mishev @Aleks1908 )

2023-02-08 13:45 UTC, Aleks1908 approved these changes
I think everything looks nice on both desktop and mobile

2023-02-08 13:53 UTC, merged