#103 Jobs-Section
AUBGTheHUB/spa-website-2022 pull request #204
Opened 2023-02-04 19:43 UTC by DemonHashira

Completed the front-end part of the Jobs-Section.

2023-02-04 23:30 UTC, asynchroza commented
There is overflow on the x axis for mobile devices. This is probably treason why there is a white bar on the right. This should be resolved.

2023-02-04 23:41 UTC, asynchroza requested changes

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/JobsSection.jsx
> +            <div className="jobs">
Extract this in a component called `JobCard`

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/JobsSection.jsx
> +            {/* <div className='searchBar'>
Remove commented code

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +
Remove commented code

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +    height: 125vh;
Instead of `height` use `min-height: 100vh`. This way the page will scale up when job cards are taking more space.

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +.photo img {
Please, don't use such global class names. Call this one `jobs-photo-container` or reference it through it's parent div.

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +.text,
Here's as well. Try to avoid such names.

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +.button-container {
-> `jobs-button-container`

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +button {
Don't reference global elements. Reference it through a class.

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +@media only screen and (min-width: 1000px) and (max-width: 1035px) {
Do you need this? There is only 35px in between. Probably you should refactor this.

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +@media only screen and (min-width: 600px) and (max-width: 783px) {
This one and the one below are conflicting with each other. Not that one doesn't take a precedence but it's too much redundant code. Refactor.

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +@media only screen and (min-width: 400px) and (max-width: 500px) {
You don't need the `min-width` here. You have a query for `max-width: 400px` below which would take precedence.

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +        width: 101vw;
width of `101vw` ? This might be one of the reasons for the "overflow"..

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +        height: 405vh;
remove heights from queries and instead you should set a global `min-height` for the container

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +        width: 101vw;
^^

2023-02-04 23:41 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/jobs_section.css
> +    .jobs {
Last reminder to use more descriptive class names

2023-02-05 00:02 UTC, asynchroza commented
![image](https://user-images.githubusercontent.com/104720011/216794697-6382fe39-cfb7-46e7-a7df-6748e0b1d83e.png)

2023-02-14 12:12 UTC, SuelaCark commented
Since @Aleks1908 worked on this ticket on a different branch, I will close this Pull request as incomplete/duplicate.

2023-02-14 12:12 UTC, closed without merging