#253 changed size of about container on HackAUBG website
AUBGTheHUB/spa-website-2022 pull request #257
Opened 2023-02-11 12:03 UTC by Pessy1

I worked on changing the size of the about container to 80% of the page instead of 300vh.

2023-02-11 22:16 UTC, SuelaCark requested changes
Please just make the requested changes. Everything else looks good. 
Good job Slavcho.

2023-02-11 22:16 UTC, SuelaCark commented on packages/web/src/components/spa/Navigation/DesktopNav/desktop_navbar.css
> +@media only screen and (max-width: 1073px) {
All changes from the file desktop_navbar.css should be deleted from here. You have probably created this branch from another branch. Please next time checkout to master before creating a new branch.

2023-02-21 23:38 UTC, SuelaCark commented
@Aleks1908 Please review this PR^^

2023-02-22 09:29 UTC, Aleks1908 approved these changes
LGTM

2023-02-22 12:44 UTC, SuelaCark commented
@asynchroza Please review and merge this branch to master

2023-02-22 13:43 UTC, merged