#248 simplify grading criteria section
AUBGTheHUB/spa-website-2022 pull request #260
Opened 2023-02-11 13:51 UTC by Eldi47

Combined the GradingSectionMobile and Desktop into one file for .css and one for .jsx. Changed the format from `<table>` to 
a hierarchy of divs. Modified the font sizes.

2023-02-11 14:14 UTC, asynchroza commented on spa-website-2022
> -Subproject commit a99d9c65c017628ef3f7425e9c69936eac364cdb
Please remove this

2023-02-11 22:03 UTC, SuelaCark requested changes
While the mobile responsiveness looks generally good. This section lacks desktop responsiveness. 
Please look at the following screenshots for more details.

![image](https://user-images.githubusercontent.com/77395265/218282997-1e5c4d4b-5bb5-4622-b9d1-29f97bae25b6.png) --> The table is too small for the laptop width (at least for my laptop)
![image](https://user-images.githubusercontent.com/77395265/218282867-b87782bd-9cde-4f29-8b31-1d2d506b5792.png) --> check height responsiveness
![image](https://user-images.githubusercontent.com/77395265/218282895-a537a8e3-fae1-4f75-9917-061726b5b1ac.png) --> height breaks the div container
![image](https://user-images.githubusercontent.com/77395265/218282908-b3280489-519d-4704-a4f6-be45d0090711.png) --> too much space after the section

2023-02-27 12:23 UTC, asynchroza approved these changes
@SuelaCark feel free to merge if everything looks alright to you (you have to approve it btw)

2023-02-27 12:33 UTC, SuelaCark approved these changes

2023-02-27 12:38 UTC, merged