#103 jobs section
AUBGTheHUB/spa-website-2022 pull request #267
Opened 2023-02-14 09:41 UTC by Aleks1908

Remade Jobs Page

2023-02-14 22:36 UTC, Aleks1908 commented on packages/web/src/components/spa/JobsSection/JobsSection.jsx
> +                        <div key={index} className="jobs-card">
I need card-section to separate all the cards from the navigation  and i need jobs-card because if the key={index}

2023-02-14 22:38 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/JobsSection.jsx
> +                        <div key={index} className="jobs-card">
Previous sentence seems left unfinished 😆. Never mind that, you can do `<JobsCard key={index}/>`

2023-02-14 22:48 UTC, Aleks1908 commented on packages/web/src/components/spa/JobsSection/JobsSection.jsx
> +                        <div key={index} className="jobs-card">
I will try to remove it but the way i've written the css it may require a lot reworking

2023-02-14 22:52 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/JobsCard.jsx
> +        <div className="card-content">
Just add jobs-card div as the outside div here and it should be fine. Please update the css name of this line, it's too generic and people might get conflicting css.

2023-02-14 23:01 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/JobsSection.jsx
> +                    <div className="jobs-card">
Last thing, can you change this to jobs-section-body or something like this. The div name is not correctly portraying what it holds.

2023-02-14 23:01 UTC, asynchroza commented on packages/web/src/components/spa/JobsSection/JobsSection.jsx
> +                    className="card-section"
Need A bit less generic div classname.

2023-02-14 23:08 UTC, asynchroza submitted a review, later dismissed

2023-02-14 23:08 UTC, Aleks1908 commented
We still need to make design for the "Jobs Not Found Screen" @SuelaCark

2023-02-15 22:44 UTC, asynchroza approved these changes

2023-02-16 01:28 UTC, asynchroza approved these changes

2023-02-16 01:29 UTC, asynchroza requested changes

2023-02-16 01:29 UTC, asynchroza commented on .github/workflows/discord.yml
> +  pull_request:
This file shouldn't exist here. Delete it.

2023-02-16 08:57 UTC, asynchroza approved these changes

2023-02-16 09:13 UTC, merged