#232 Fix favicon rendering logic
AUBGTheHUB/spa-website-2022 pull request #354
Opened 2023-03-04 16:27 UTC by asynchroza

2023-03-04 20:31 UTC, SuelaCark requested changes
For some reason, every time you go from HackAUBG to the landing page through clicking the Hub Logo, the favicon still stays green unless the page is either refreshed or you click on the jobs section.

2023-03-04 23:51 UTC, asynchroza commented
@SuelaCark @Aleks1908 up for verification

2023-03-05 11:29 UTC, SuelaCark requested changes
Please check the comments. Everything else about the favicon works perfectly.

2023-03-05 11:29 UTC, SuelaCark commented on packages/web/src/components/spa/AboutSection/AboutSection.jsx
>              <div className="about-image">
To what I noticed, the about section anchor in the landing page is mistakenly connected to the one from the hackaubg instead. Hence, when you click the About anchor in Hackaubg nothing happens, but when you got then to the landing page, it loads immediately to the about us section.

2023-03-05 11:29 UTC, SuelaCark commented on packages/web/src/components/spa/MainPage.jsx
>          new Anchor('Team', '#team'),
As mentioned above, please make sure the About section anchor for landing page is connected correctly.

2023-03-05 12:26 UTC, asynchroza commented
@SuelaCark please verify again. I couldn't come up with a clean solution on how to load at top level and I don't have the time to do so. The implemented scrolling looks nice to me, if it's alright with you, feel free to approve and merge

2023-03-05 12:52 UTC, SuelaCark approved these changes

2023-03-05 12:52 UTC, merged