#808 Implements verification logic and tests for random participants
AUBGTheHUB/spa-website-2022 pull request #827
Opened 2024-12-27 18:08 UTC by Alexandr-Ignatov

#808 Implements verification logic and tests for random participants

# Changes
##1. verification_service.py
Added a new method verify_random_participant:
- Accepts participant_id and team_id (from the decoded JWT payload).
- Performs Capacity Check 1 if team_id is not provided.
- Leverages the existing check_capacity_register_random_participant_case method from HackathonService in participant_service.py.
- Raises an HTTPException with a 409 status code if the hackathon capacity is full.
- Logs verification success for debugging purposes.
Reused existing logic to ensure consistency and avoid duplication of the capacity check.

##2. verification_handler.py
Added verify_participant endpoint:
- Accepts a jwt_token as a query parameter.
- Decodes the token using jose to extract participant_id, is_admin, and team_id.
- Validates that is_admin is false, indicating the participant is random.
- Delegates the verification logic to the VerificationService.
- Returns a JSON response indicating successful verification or appropriate errors for invalid tokens or capacity issues.
Added type annotations for the handler method:
- jwt_token: str for the JWT parameter.
- service: VerificationService for the dependency.
- -> dict[str, str] for the return type to ensure type safety.

##3. test_verification_service.py
Added unit tests for the verify_random_participant method in VerificationService:
- test_verify_random_participant_success:
     Verifies the participant successfully when the capacity check passes.
     Uses AsyncMock to mock HackathonService and simulate capacity availability.
- test_verify_random_participant_capacity_full:
     Tests that the service raises a 409 HTTPException when the hackathon is at full capacity.
     Ensures the capacity check logic is invoked correctly.
Provided type annotations (-> None) for all test functions.

##4. test_verification_handler.py
Added unit tests for the verify_participant handler:
- test_verify_participant_success:
     Simulates a valid JWT and ensures the handler delegates the logic to VerificationService.
     Asserts a 200 success response with the correct JSON message.
- test_verify_participant_invalid_token:
    Tests that an invalid JWT returns a 401 Unauthorized error.
- test_verify_participant_invalid_payload:
   Ensures a 400 Bad Request error is raised when the JWT payload is missing is_admin or has invalid data.
Added appropriate type annotations for test functions:
- test_client fixture: TestClient
- mock_service fixture: AsyncMock

2024-12-27 19:10 UTC, Isak-Bego requested changes
Hey Alex, 
You need to change quite a bit from how you have structured your code. Please review the changes that Lubomira has made together with the comments of Ivan and try to work something out. Here is the link to that: https://github.com/AUBGTheHUB/monolith/pull/817/files

I want you to first focus on getting the logic and structure right and then writing tests for it. I will be here for any questions that you might have. 

Keep it up! You are on the right track! Thank you Alex!

2024-12-27 19:11 UTC, Isak-Bego commented on services/py-api/src/server/handlers/verification_handler.py
> +from jose import jwt, JWTError
"jose" is a typo, that is why the tests are breaking. Please fix it.

2025-01-07 17:18 UTC, asynchroza commented on services/py-api/src/database/repository/participants_repository.py
> +            # The ReturnDocument.after return the updated document instead of the orignal document which is the
```suggestion
            # ReturnDocument.AFTER returns the updated document instead of the orignal document which is the
```

2025-01-07 17:41 UTC, asynchroza commented on services/py-api/src/server/handlers/verification_handler.py
> +                return ErrResponse(error="The participant was not found")
Isn't `ErrResponse` already taking care of the `status_code`?

```python
return ErrResponse(error="The participant was not found", status_code=status.HTTP_404_NOT_FOUND)
```

2025-01-07 18:27 UTC, asynchroza commented on services/py-api/src/server/handlers/verification_handler.py
> +                return ErrResponse(error="The participant was not found")
@Isak-Bego

2025-01-07 19:12 UTC, Isak-Bego reviewed
I made some changes in the logic and now everything is working correctly. You can proceed with unit and integration tests

2025-01-07 19:20 UTC, Isak-Bego commented on services/py-api/src/server/handlers/verification_handler.py
> +                return ErrResponse(error="The participant was not found")
This is the implementation of ErrResponse: 

```Python
from typing import Dict, Any, Optional

from pydantic import BaseModel, field_serializer, ConfigDict

from src.database.model.participant_model import Participant
from src.database.model.team_model import Team

# https://fastapi.tiangolo.com/tutorial/response-model/#response_model-parameter


class ErrResponse(BaseModel):
    error: str
```

2025-01-07 19:22 UTC, Isak-Bego commented on services/py-api/src/server/handlers/verification_handler.py
> +                return ErrResponse(error="The participant was not found")
So no, it is not taking care of the status_code.

2025-01-08 20:42 UTC, asynchroza commented on services/py-api/src/server/handlers/verification_handler.py
> +                return ErrResponse(error="The participant was not found")
If you return this instance but not explicitly update the response's status code, does it default to `500`? If not, that's poor developer experience.

2025-01-10 16:13 UTC, iobreshkov-qb commented on services/py-api/src/server/handlers/verification_handler.py
> +                return ErrResponse(error="The participant was not found")
@asynchroza We make the route return a default 500 status code

```python
@router.get(
    "/{object_id}",
    status_code=500,
    responses={200: {"model": TeamDeletedResponse}, 404: {"model": ErrResponse}},
    dependencies=[Depends(is_auth), Depends(validate_obj_id)],
)
```
If we want to keep returning models, we have to [change the default status code ](https://fastapi.tiangolo.com/advanced/response-change-status-code/#use-case)of the Response Starlette obj. Unfortunately, there isn't a much better way. 

`responses={200: {"model": TeamDeletedResponse}, 404: {"model": ErrResponse}}` this line is for the Swagger Docs, here is some more info:

<img width="913" alt="image" src="https://github.com/user-attachments/assets/613c4143-1875-466e-9d03-1c7c2671b2ba" />
<img width="685" alt="image" src="https://github.com/user-attachments/assets/b09f3bbd-dfb2-466c-aa4e-e53930634cb7" />

An alternative would be to leave `responses={200: {"model": TeamDeletedResponse}, 404: {"model": ErrResponse}}` in order for swagger to detect it and do:
```python
   return JSONResponse(
        content=ModelRespone(message="something").model_dump(),
        status_code=201
    )
```

which I am not sure is the best option either.

Another alternative would be:

```python

from fastapi.responses import JSONResponse
from pydantic import BaseModel


class PongResponse(BaseModel):
    message: str


class CustomResponse(JSONResponse):
    def __init__(self, content: BaseModel, status_code: int = 200):
        super().__init__(content=content.model_dump(), status_code=status_code)

@utility_router.get("/ping", response_model=PongResponse)
async def ping():
    return CustomResponse(content=PongResponse(message="pong"), status_code=201)
```

please let me know what you think.

2025-01-10 17:22 UTC, asynchroza commented on services/py-api/src/server/handlers/verification_handler.py
> +                return ErrResponse(error="The participant was not found")
```python
@utility_router.get("/ping", response_model=PongResponse)
async def ping():
    return Response(content=PongResponse(message="pong"), status_code=201)
```

Yes

2025-01-16 12:27 UTC, closed without merging

2025-01-16 12:27 UTC, Isak-Bego commented
Continued at #841